### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by robinweide** [COMBINE-lab/matryoshka#1]
Hi there,

I read your paper with  great interest and would like to try your tool.

Using boost from [Homebrew](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/boost.rb), I compiled your code per your instructions. 
However, I get a _Segmentation fault 11_ at different times, when changing the size of the matrix. Even very small matrices seem to cause a Segfault11.

Could you please help?

Thanks,

Robin

---

Specs:
- MacBook Pro (Retina, 13-inch, Late 2013)
- 2,8 GHz Intel Core i7
- 16 GB 1600 MHz DDR3

**Comment by laraib85** [comment]
Hi, 

Thanks for your interest in the tool. Could you send me the file you're trying to run the tool on? I'll look into the issue.

**Comment by robinweide** [comment]
Awesome!
I just used your [example-matrix](https://github.com/COMBINE-lab/matryoshka/blob/master/example/nij.chr19.new.gz) and sub-samples of it.

**Comment by rob-p** [comment]
@laraib85 --- such segfaults are usually the result of trying to access an array out of bounds somewhere (which has undefined behavior and thus makes reproducing things difficult).  We might try adding `-D _GLIBCXX_DEBUG` to the compiler flags to turn on bounds checking for all vector accesses to see if that helps us catch it.

**Comment by laraib85** [comment]
@robinweide hey, try running it now. Fixed the bug, should be fine. Thanks!

**Comment by robinweide** [comment]
Tried installing it on my Mac with the following error (will try on my Ubuntu-desktop tomorrow):

> [ 20%] Building CXX object src/CMakeFiles/matryoshka.dir/Matryoshka.cpp.o
> cd /Users/robin/bin/matryoshka-master/src && /Users/robin/bin/matryoshka-master/clang++    -O3 -g -std=c++11 -Wall -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.9 -I/Users/robin/boost/include -I/Users/robin/bin/matryoshka-master/include    -o CMakeFiles/matryoshka.dir/Matryoshka.cpp.o -c /Users/robin/bin/matryoshka-master/src/Matryoshka.cpp
> /bin/sh: /Users/robin/bin/matryoshka-master/clang++: No such file or directory
> make[2]: **\* [src/CMakeFiles/matryoshka.dir/Matryoshka.cpp.o] Error 127
> make[1]: **\* [src/CMakeFiles/matryoshka.dir/all] Error 2
> make: **\* [all] Error 2

**Comment by laraib85** [comment]
I didn't make any changes to the make files so it should compile as before. It can't find clang. Make sure the program can access the correct folder where clang is installed.

**Comment by rob-p** [comment]
Yes; this looks like a failure to find the compiler.  Strangely, it seems it's looking for it in the `matryoshka` directory!  @robinweide  --- can you post the output of the command `$ clang++ -v`, and also `$ which clang++`?  I would recommend completely removing the `build` directory and trying to make again from scratch.  This build compiles cleanly on my macbook pro with clang version `Apple LLVM version 7.0.2 (clang-700.1.81)`.

**Comment by robinweide** [comment]
Got it to compile on my desktop with:

> cmake -DMAKE_C_COMPILER=/usr/bin/clang -DMAKE_CXX_COMPILER=/usr/bin/clang++ -DBOOST_ROOT=$HOME/boost -DBOOST_NO_SYSTEM_PATHS=true

Thanks everybody! :+1:
